INFO 2023-07-09 13:23:00,533 root the number entered by user is 3 and 9
INFO 2023-07-09 13:23:00,533 root we are into the try block
INFO 2023-07-09 13:23:00,533 root this line is print when div=a/b opration performs successflly 
INFO 2023-07-09 13:23:00,533 root result of the code is 0.3333333333333333
INFO 2023-07-09 13:23:26,970 root the number entered by user is 3 and 0
INFO 2023-07-09 13:23:26,971 root we are into the try block
ERROR 2023-07-09 13:23:26,971 root division by zero
Traceback (most recent call last):
  File "C:\Users\swapn\PycharmProjects\Logging\logging INFO.py", line 8, in division
    div = a/b
ZeroDivisionError: division by zero
